version: 2.1

workflows:
  build_workflow:
    jobs:
      - build_job:
          context:
            - omdr

jobs:
  build_job:
    docker:
      - image: gcc:10.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /cdsc

    steps:
      - checkout

      - run:
          name: Installing build dependencies
          command: |
            sh script/cibuild \
            export PATH=$PATH:$HOME/.local/bin

      - run: meson setup builddir

      - run: meson compile -C builddir
