version: 2.1

jobs:
  
  # Building with GCC
  build_job_gcc:
    docker:
      - image: gcc:10.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /cdsc

    steps:
      - checkout

      - run:
          name: Installing build dependencies
          command: |
            sh script/cibuild \
            export PATH=$PATH:$HOME/.local/bin

      - run: meson setup builddir

      - run: meson compile -C builddir

  # Building with clang
  build_job_clang:
    docker:
      - image: silkeh/clang:10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /cdsc

    steps:
      - checkout

      - run:
          name: Installing build dependencies
          command: |
            sh script/cibuild \
            export PATH=$PATH:$HOME/.local/bin

      - run: meson setup builddir

      - run: meson compile -C builddir

workflows:
  build_workflow:
    jobs:
      - build_job_clang:
          context: omdr
      - build_job_gcc:
          context: omdr
