#!/bin/bash

# script/bootstrap: Install dependencies that the application requires 
#                   for building and running.

set -e

cd "$(dirname "$0")/.."

echo "==> Updating..."
apt-get update;

echo "==> Installing build tools..."
apt-get -y install python3 python3-pip python3-setuptools python3-wheel \
                ninja-build

echo "==> Installing python dependencies..."
pip3 install --upgrade meson

echo "Bootstraping is done"
