#!/bin/bash

# script/bootstrap: Install dependencies that the application requires 
#                   for building and running.

set -e

ROOT="$(dirname "$0")/.." 
BUILD_DIR=builddir
PROJ_NAME=cdsc
ARTIFACTS_ROOT=$BUILD_DIR/artifacts
ARTIFACTS=$ARTIFACTS_ROOT/$PROJ_NAME
ARTIFACTS_LIB=$ARTIFACTS/lib
ARTIFACTS_INCLUDE=$ARTIFACTS/include
ARTIFACTS_EXAMPLES=$ARTIFACTS/examples
COMPRESSED_ARTIFACTS=$BUILD_DIR/compressed-artifacts

cd $ROOT

echo "==> Updating..."
apt-get update;

echo "==> Installing build tools..."
apt-get -y install python3 python3-pip python3-setuptools python3-wheel \
    ninja-build

echo "==> Installing python dependencies..."
pip3 install --upgrade meson
export PATH=$PATH:$HOME/.local/bin

echo "==> Running meson steps..."
rm -rf $BUILD_DIR
meson setup $BUILD_DIR
meson compile -C $BUILD_DIR
meson test -C $BUILD_DIR

echo "==> Collecting artifacts..."
mkdir -p $ARTIFACTS_LIB $ARTIFACTS_INCLUDE $ARTIFACTS_EXAMPLES $COMPRESSED_ARTIFACTS

cp $BUILD_DIR/libcdsc.a $ARTIFACTS_LIB
cp $BUILD_DIR/libcdsc.so $ARTIFACTS_LIB
cp src/* $ARTIFACTS_INCLUDE
cp -r $BUILD_DIR/examples/zstd_map $ARTIFACTS_EXAMPLES

echo "==> Compressing artifacts..."
tar -czvf $COMPRESSED_ARTIFACTS/$PROJ_NAME.tar.gz -C $ARTIFACTS_ROOT $PROJ_NAME

cd $ROOT


echo "CI build is done"
