#!/bin/bash

# scripts/cover: Run code coverage using gcovr

set -eux

ROOT="$(dirname "$0")/.." 
BOOTSTRAP=$ROOT/scripts/bootstrap
BUILD_DIR=builddir_coverage
PROJ_NAME=gcovr
ARTIFACTS_ROOT=$BUILD_DIR/artifacts
ARTIFACTS_GCOVR=$ARTIFACTS_ROOT/$PROJ_NAME
ARTIFACTS_GCOVR_HTML=$ARTIFACTS_GCOVR/html
COMPRESSED_ARTIFACTS=$BUILD_DIR/compressed-artifacts

cd $ROOT

echo "==> Calling bootsrap..."
./$BOOTSTRAP
export PATH=$PATH:$HOME/.local/bin

echo "==> Running meson steps..."
rm -rf $BUILD_DIR
meson $BUILD_DIR -Db_coverage=true
meson compile -C $BUILD_DIR
meson test -C $BUILD_DIR
ninja coverage -C $BUILD_DIR

echo "==> Collecting artifacts..."
mkdir -p $ARTIFACTS_GCOVR_HTML $COMPRESSED_ARTIFACTS

cp $BUILD_DIR/meson-logs/coverage.xml $ARTIFACTS_GCOVR
cp $BUILD_DIR/meson-logs/coverage.txt $ARTIFACTS_GCOVR
cp -r $BUILD_DIR/meson-logs/coveragereport/* $ARTIFACTS_GCOVR_HTML

echo "==> Compressing artifacts..."
tar -czvf $COMPRESSED_ARTIFACTS/$PROJ_NAME.tar.gz -C $ARTIFACTS_ROOT $PROJ_NAME

cd $ROOT


echo "Covering is done"
